train:
  # Resize: thay đổi kích thước ảnh về chuẩn để đưa vào model
  Resize:
    size_h: 244
    size_w: 244

  # Transform: Agmentation (Chỉ áp dụng trong training thôiii)
  transform:
    affine_transform_degree: 20       # góc xoay ±20 độ
    affine_translate_percent: 0.1     # dịch chuyển ±10% chiều cao/chiều rộng
    affine_scale: [0.8, 1.2]          # scale ảnh trong khoảng [0.8, 1.2]
    affine_shear: 20                  # shear (nghiêng) ±20 độ
    elastic_transform_alpha: 10       # hệ số alpha cho phép biến dạng đàn hồi
    elastic_transform_sigma: 15       # hệ số sigma cho phép làm mượt biến dạng đàn hồi
    p: 1.0                            # xác suất áp dụng toàn bộ chuỗi augmentation (1.0 = luôn áp dụng)

valid:
  # Chỉ resize, không áp dụng augmentation để đánh giá ổn định
  Resize:
    size_h: 244  # chiều cao sau khi resize
    size_w: 244  # chiều rộng sau khi resize

test:
  # Chỉ resize, không augmentation, dùng cho inference/kiểm thử
  Resize:
    size_h: 244  # chiều cao sau khi resize
    size_w: 244  # chiều rộng sau khi resize
