# Setup cho Training
train:  
  pin_memory: True    # ghim dữ liệu lên CPU trước khi đưa sang GPU
  shuffle: True       # xáo trộn dữ liệu mỗi epoch
  drop_last: True     # bỏ batch cuối nếu không đủ batch_size
  num_workers: 0      # số luồng load data (0 = load trên main thread)
  batch_size: 4       # số sample mỗi batch

# Setup cho Validate
valid:
  pin_memory: True    # ghim dữ liệu lên CPU trước khi đưa sang GPU
  shuffle: False      # không xáo trộn để đánh giá ổn định
  drop_last: False    # giữ cả batch cuối dù thiếu sample
  num_workers: 0      # số luồng load data
  batch_size: 4       # số sample mỗi batch

# Setup cho Test
test:
  pin_memory: True    # ghim dữ liệu lên CPU trước khi đưa sang GPU
  shuffle: False      # không xáo trộn để kết quả khớp nhãn
  drop_last: False    # giữ cả batch cuối dù thiếu sample
  num_workers: 4      # sử dụng 4 luồng để load data nhanh hơn
  batch_size: 6       # số sample mỗi batch (có thể lớn hơn valid/train)